name: handyman_app
description: A new Flutter project.

publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.6
  flutter_launcher_icons: ^0.13.1

  # Firebase core dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.3.8
  firebase_messaging: ^14.6.8
  flutter_background_service: ^5.1.0

  # Common UI & utilities
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  intl: ^0.20.2
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  image_cropper: ^9.1.0
  google_maps_flutter: ^2.3.0
  flutter_local_notifications: ^19.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/icon.png
    - assets/welcome.png
