name: test2
description: A new Flutter project.

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.8.0
  flutter_stripe: ^11.3.0
  http: ^1.1.0  # Already in your dependencies
  cupertino_icons: ^1.0.8
  intl: ^0.18.0 # Add this line for date formatting
  firebase_database: ^10.4.0
  google_maps_flutter: ^2.10.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0  # Use a newer version
  geocoding: ^3.0.0
  share_plus: ^7.0.0
  permission_handler: ^11.3.0
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^19.1.0
  image_picker: ^1.0.4
  image_cropper: ^9.1.0 
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
  assets:

    - assets/icon.png
    - assets/handyman_marker.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"