version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --cors
      - "*"
      - --enable-api
      - --model
      - models
      - --endpoints
      - endpoints.yml
    depends_on:
      - action-server

  action-server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
      - ./config:/app/config
